### ISSUE TITLE
BV Questions disabled cause a console error on PDP

### ISSUE THREAD

**Issue by valenciaisaza** [bazaarvoice/magento2-extension#63] opened 2019-10-11 15:58 UTC
Hi,

A lack of a validation about the Questions enable configuration is needed on the file:
view/frontend/templates/productheader.phtml (line 54)

If not, I get a console error: 
TypeError: BV.questions is undefined

(maybe the same is need fo the reviews at line 51)

Thanks

**Comment by jantzenw** [comment] 2019-10-24 20:13
This should be fixed in v8.1.3 of the extension. Please try that version and confirm that the issue is resolved.

**Closed** 2020-07-10 13:56 UTC
